local_backend: true

logo_url: /logo.svg

backend:
    name: "github"
    repo: smokeyfro/astros
    branch: main
    base_url: https://auth.smokeyfro.com
    automatic_deployments: true

media_folder: "public/images"
public_folder: "/images"

i18n:
    structure: "multiple_folders"
    locales: ["en", "nl"]
    default_locale: "en"

collections:
    - name: "massage"
      i18n: true
      label: "Massage"
      folder: "src/content/massage"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Title"
            i18n: true
          - label: "Image"
            name: "image"
            widget: "object"
            i18n: true
            fields:
                - { label: Source, name: src, widget: image, i18n: "duplicate" }
                - { label: Alt Text, name: alt, widget: string, i18n: true }
          - name: "body"
            widget: "markdown"
            label: "Content"
            i18n: true
  - name: "metadata"
    label: "Settings"
    icon: "settings"
    extension: "yml"
    format: "yml"
    files:
      - file: "src/content/settings.yml"
        label: "Site metadata"
        name: "metadata"
        fields:
          - { label: "Site Title", name: "title", widget: "string", hint: "Your site's title, used for branding and SEO." }
          - { label: "Site Description", name: "description", widget: "text", hint: "Your site's description, used for SEO." }
          - { label: "Site URL", name: "url", widget: "string", hint: "Your live site's full URL." }
          - { label: "Language", name: "language", widget: "string", hint: "The language your site is written in." }