local_backend: true

logo_url: /logo.svg

backend:
    name: "github"
    repo: smokeyfro/astros
    branch: main
    base_url: https://auth.smokeyfro.com
    automatic_deployments: true

media_folder: "public/images"
public_folder: "/images"

i18n:
    structure: "multiple_folders"
    locales: ["en", "nl"]
    default_locale: "en"

collections:
    - name: "posts"
      i18n: true
      label: "Massage"
      folder: "src/content/blog"
      create: true
      delete: true
      fields:
          - name: "title"
            widget: "string"
            label: "Post Title"
            i18n: true
          - label: "Draft"
            name: "draft"
            widget: "boolean"
            i18n: "duplicate"
          - label: "Image"
            name: "image"
            widget: "object"
            i18n: true
            fields:
                - { label: Source, name: src, widget: image, i18n: "duplicate" }
                - { label: Alt Text, name: alt, widget: string, i18n: true }
          - name: "body"
            widget: "markdown"
            label: "Post Body"
            i18n: true
